<wsdl:definitions
     name="UpdateAUSSNTransaction"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ebonding_osb_app/AzureADUserSync/UpdateAUSSNTransaction"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ebonding_osb_app/AzureADUserSync/UpdateAUSSNTransaction"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateAUSSNTransaction"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="UpdateAUSSNTransaction_plt" >
    <plt:role name="UpdateAUSSNTransaction_role" >
      <plt:portType name="tns:UpdateAUSSNTransaction_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateAUSSNTransaction" schemaLocation="UpdateAUSSNTransaction_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="AusSnTransactionsCollection_msg">
        <wsdl:part name="AusSnTransactionsCollection" element="top:AusSnTransactionsCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateAUSSNTransaction_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:AusSnTransactionsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
