<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Insert_ESB_Audit" name="Insert_ESB_Audit-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="Insert_ESB_Audit.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Insert_ESB_Audit"/>
    <wsdl:binding name="Insert_ESB_Audit_ptt-binding" type="ins:Insert_ESB_Audit_ptt" xmlns:ins="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Insert_ESB_Audit">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>