<wsdl:definitions name="UpdateAUSTransaction" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ebonding_osb_app/AzureADUserSync/UpdateAUSTransaction" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ebonding_osb_app/AzureADUserSync/UpdateAUSTransaction" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateAUSTransaction" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="UpdateAUSTransaction_plt">
    <plt:role name="UpdateAUSTransaction_role">
      <plt:portType name="tns:UpdateAUSTransaction_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateAUSTransaction" schemaLocation="UpdateAUSTransaction_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="AusTransactionsCollection_msg">
        <wsdl:part name="AusTransactionsCollection" element="top:AusTransactionsCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateAUSTransaction_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:AusTransactionsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>