<DefaultValues>
  <Inbound>
    <Priority>1</Priority>
    <Category>Hardware</Category>
  </Inbound>
  <Outbound>
    <UserLastName>BA-SITAWAN-CNT</UserLastName>
    <UserPhoneNumber>XXXXXXXXXXX</UserPhoneNumber>
    <PrimaryCI>BA-SITAWAN</PrimaryCI>
    <SecondaryCI>ROUTER_NAME</SecondaryCI>
  </Outbound>
</DefaultValues>