<wsdl:definitions name="Fetch_EbondingsPriorityMappingOutbound" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsPriorityMappingOutbound" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsPriorityMappingOutbound" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/Fetch_EbondingsPriorityMappingOutbound" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="Fetch_EbondingsPriorityMappingOutbound_plt">
    <plt:role name="Fetch_EbondingsPriorityMappingOutbound_role">
      <plt:portType name="tns:Fetch_EbondingsPriorityMappingOutbound_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Fetch_EbondingsPriorityMappingOutbound" schemaLocation="Fetch_EbondingsPriorityMappingOutbound_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="Fetch_EbondingsPriorityMappingOutboundSelect_inputParameters">
        <wsdl:part name="Fetch_EbondingsPriorityMappingOutboundSelect_inputParameters" element="top:Fetch_EbondingsPriorityMappingOutboundSelect_rectype_impact_urgencyInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EbondingsPriorityMappingCollection_msg">
        <wsdl:part name="EbondingsPriorityMappingCollection" element="top:EbondingsPriorityMappingCollection"/>
    </wsdl:message>
    <wsdl:portType name="Fetch_EbondingsPriorityMappingOutbound_ptt">
        <wsdl:operation name="Fetch_EbondingsPriorityMappingOutboundSelect">
            <wsdl:input message="tns:Fetch_EbondingsPriorityMappingOutboundSelect_inputParameters"/>
            <wsdl:output message="tns:EbondingsPriorityMappingCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>