<wsdl:definitions name="Fetch_EbondingsPriorityMappingInbound" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsPriorityMappingInbound" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsPriorityMappingInbound" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/Fetch_EbondingsPriorityMappingInbound" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="Fetch_EbondingsPriorityMappingInbound_plt">
    <plt:role name="Fetch_EbondingsPriorityMappingInbound_role">
      <plt:portType name="tns:Fetch_EbondingsPriorityMappingInbound_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Fetch_EbondingsPriorityMappingInbound" schemaLocation="Fetch_EbondingsPriorityMappingInbound_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="Fetch_EbondingsPriorityMappingInboundSelect_inputParameters">
        <wsdl:part name="Fetch_EbondingsPriorityMappingInboundSelect_inputParameters" element="top:Fetch_EbondingsPriorityMappingInboundSelect_rectype_priorityInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EbondingsPriorityMappingCollection_msg">
        <wsdl:part name="EbondingsPriorityMappingCollection" element="top:EbondingsPriorityMappingCollection"/>
    </wsdl:message>
    <wsdl:portType name="Fetch_EbondingsPriorityMappingInbound_ptt">
        <wsdl:operation name="Fetch_EbondingsPriorityMappingInboundSelect">
            <wsdl:input message="tns:Fetch_EbondingsPriorityMappingInboundSelect_inputParameters"/>
            <wsdl:output message="tns:EbondingsPriorityMappingCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>