<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsPriorityMappingInbound" name="Fetch_EbondingsPriorityMappingInbound-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="Fetch_EbondingsPriorityMappingInbound.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsPriorityMappingInbound"/>
    <wsdl:binding name="Fetch_EbondingsPriorityMappingInbound_ptt-binding" type="fet:Fetch_EbondingsPriorityMappingInbound_ptt" xmlns:fet="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsPriorityMappingInbound">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Fetch_EbondingsPriorityMappingInboundSelect">
            <soap:operation soapAction="Fetch_EbondingsPriorityMappingInboundSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>