<DefaultValues>
	<CUSTOMER_LOC>IS-INT UNKNOWN CONTACT</CUSTOMER_LOC>
	<SEVERITY>3</SEVERITY>
	<CATEGORY>Failure</CATEGORY>
	<CATEGORY_UNMAPPED>2</CATEGORY_UNMAPPED>
	<REPORT_METHOD>Automated</REPORT_METHOD>
	<DEF_GROUP>AUTOASSIGNMENT PROCESS</DEF_GROUP>
	<PRO_ACT_DEF_GROUP>AUTOASSIGNMENT PROCESS</PRO_ACT_DEF_GROUP>
	<Service_CI>GENERIC_UNKNOWN_SERVICE_CI</Service_CI>
	<zservicedesk_group>ADS-AMMAN QUEUE MANAGERS</zservicedesk_group>
</DefaultValues>