<wsdl:definitions name="Fetch_EbondingsCategoryMappingInbound" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsCategoryMappingInbound" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/Common/Fetch_EbondingsCategoryMappingInbound" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/Fetch_EbondingsCategoryMappingInbound" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="Fetch_EbondingsCategoryMappingInbound_plt">
    <plt:role name="Fetch_EbondingsCategoryMappingInbound_role">
      <plt:portType name="tns:Fetch_EbondingsCategoryMappingInbound_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Fetch_EbondingsCategoryMappingInbound" schemaLocation="Fetch_EbondingsCategoryMappingInbound_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="Fetch_EbondingsCategoryMappingInboundSelect_inputParameters">
        <wsdl:part name="Fetch_EbondingsCategoryMappingInboundSelect_inputParameters" element="top:Fetch_EbondingsCategoryMappingInboundSelect_recType_shCategory_isActiveInputParameters"/>
    </wsdl:message>
    <wsdl:message name="EbondingsCategoryMappingCollection_msg">
        <wsdl:part name="EbondingsCategoryMappingCollection" element="top:EbondingsCategoryMappingCollection"/>
    </wsdl:message>
    <wsdl:portType name="Fetch_EbondingsCategoryMappingInbound_ptt">
        <wsdl:operation name="Fetch_EbondingsCategoryMappingInboundSelect">
            <wsdl:input message="tns:Fetch_EbondingsCategoryMappingInboundSelect_inputParameters"/>
            <wsdl:output message="tns:EbondingsCategoryMappingCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>