<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/DataMappingLoad/Insert_Ebondings_Data_Mapping" name="Insert_Ebondings_Data_Mapping-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="Insert_Ebondings_Data_Mapping.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/DataMappingLoad/Insert_Ebondings_Data_Mapping"/>
    <wsdl:binding name="Insert_Ebondings_Data_Mapping_ptt-binding" type="ins:Insert_Ebondings_Data_Mapping_ptt" xmlns:ins="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/DataMappingLoad/Insert_Ebondings_Data_Mapping">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="merge">
            <soap:operation soapAction="merge"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>