<wsdl:definitions name="Insert_Ebondings_Priority_Mapping" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/DataMappingLoad/Insert_Ebondings_Priority_Mapping" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SITA_Ebondings/DataMappingLoad/Insert_Ebondings_Priority_Mapping" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_Ebondings_Priority_Mapping" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="Insert_Ebondings_Priority_Mapping_plt">
    <plt:role name="Insert_Ebondings_Priority_Mapping_role">
      <plt:portType name="tns:Insert_Ebondings_Priority_Mapping_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/Insert_Ebondings_Priority_Mapping" schemaLocation="Insert_Ebondings_Priority_Mapping_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="EbondingsPriorityMappingCollection_msg">
        <wsdl:part name="EbondingsPriorityMappingCollection" element="top:EbondingsPriorityMappingCollection"/>
    </wsdl:message>
    <wsdl:portType name="Insert_Ebondings_Priority_Mapping_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:EbondingsPriorityMappingCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>