<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="AUS_TransactionTableMonitoringPS"
     targetNamespace="http://xmlns.oracle.com/ebonding_osb_app/FoundationDataSync/AUS_TransactionTableMonitoringPS"
     xmlns:tns="http://xmlns.oracle.com/ebonding_osb_app/FoundationDataSync/AUS_TransactionTableMonitoringPS"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.oracle.com/ebonding_osb_app/FoundationDataSync/AUS_TransactionTableMonitoringPS"
             elementFormDefault="qualified">
            <element name="RootElement" type="string"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="executeSync" element="tns:RootElement"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="executeResponse" element="tns:RootElement"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_bind" type="tns:execute_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="execute">
            <soap:operation style="document" soapAction="execute"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/ebonding_osb_app/FoundationDataSync/AUS_TransactionTableMonitoringPS"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/ebonding_osb_app/FoundationDataSync/AUS_TransactionTableMonitoringPS"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>