<definitions targetNamespace="urn:ws.solvedirect.com/webservices/custom" name="CallServiceService" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:ws.solvedirect.com/webservices/custom" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/">
	<types>
		<xsd:schema>
			<xsd:import namespace="urn:ws.solvedirect.com/webservices/custom" schemaLocation="../Schemas/EssintialCallService.xsd"/>
		</xsd:schema>
	</types>
	<message name="SDWebServiceException">
		<part name="fault" element="tns:SDWebServiceException"/>
	</message>
	<message name="putCall">
		<part name="parameters" element="tns:putCall"/>
	</message>
	<message name="putCallResponse">
		<part name="parameters" element="tns:putCallResponse"/>
	</message>
	<portType name="CallService">
		<operation name="putCall">
			<input wsam:Action="urn:ws.solvedirect.com/webservices/custom:CallService:putCallRequest" message="tns:putCall"/>
			<output wsam:Action="urn:ws.solvedirect.com/webservices/custom:CallService:putCallResponse" message="tns:putCallResponse"/>
			<fault message="tns:SDWebServiceException" name="SDWebServiceException" wsam:Action="urn:ws.solvedirect.com/webservices/custom:CallService:putCall:Fault:SDWebServiceException"/>
		</operation>
	</portType>
	<binding name="CallServicePortBinding" type="tns:CallService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<operation name="putCall">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
			<fault name="SDWebServiceException">
				<soap:fault name="SDWebServiceException" use="literal"/>
			</fault>
		</operation>
	</binding>
</definitions>